/// El yapımı haritalar. Oyun içi Serbest Oyun kaldırıldı; bu haritalar
/// kalibrasyon referansı (BalanceLab + testler) ve Sonsuz Mod arenaları
/// olarak yaşıyor.
public enum Maps {
    // "Klasik Vadi" — suyu olmayan S-kıvrımlı orijinal harita.
    public static let classicAscii = """
    ................
    S###########....
    ...........#....
    ...........#....
    ...#########....
    ...#............
    ...#########....
    ...........#....
    ...........B....
    """

    // "Nehir Geçidi" — dikey 2 kare genişliğinde nehir (sütun 7-8), yol nehri
    // satır 3'te TEK köprüyle keser; gerisi klasik gibi S-kıvrımlı.
    public static let riverAscii = """
    .......~~.......
    S#####.~~.......
    .....#.~~.......
    .....########...
    .......~~...#...
    .......~~...#...
    .......~~.###...
    .......~~.#.....
    .......~~.B.....
    """

    public static func classic() -> MapDefinition {
        try! MapDefinition.parse(classicAscii, tileSize: Balance.tileSize)
    }

    public static func river() -> MapDefinition {
        try! MapDefinition.parse(riverAscii, tileSize: Balance.tileSize)
    }

    /// Menü seçici sırası; ad aynı zamanda kalıcı skor anahtarının ekidir.
    public static var all: [(name: String, map: MapDefinition)] {
        [("Klasik Vadi", classic()), ("Nehir Geçidi", river())]
    }
}
